import { 
  Wind, Eraser, Droplets, Trash2, BookOpen, Apple, Laptop, Sun, Dumbbell, Mic, 
  Bell, Key, Archive, Music, Coffee, Smile, HelpCircle, Calendar, Palette, Eye,
  Layers, CheckCircle2, UserCircle2, Type, Info, MousePointer2, Save,
  Zap, Loader, Sparkles, Heart, Pencil, ChevronUp, ChevronDown, Utensils, 
  Milk, Paintbrush, Scissors, Hammer, Trees, Flower2, Cloud, 
  Thermometer, Gamepad2, Dice5, Puzzle, Monitor, Smartphone, Speaker, Calculator, 
  Languages, Globe, History, Ghost, Rocket, Moon, Footprints, Bike, Bus, Map, 
  Compass, Camera, Video, Mail, Phone, Clock, List, ClipboardCheck, Sticker, 
  Award, Medal, Trophy, Shirt, Search, Library, School, Lightbulb,
  Home, Construction, Wrench, Plug, Battery, Wifi, Volume2, VolumeX, Mic2, Ear, Brain,
  Pizza, Sandwich, IceCream, Candy, Beer, Wine, Cake, 
  Car, Train, Plane, Ship, Anchor, MapPin, Navigation, 
  Target, Swords, Shield, Wand2, FlaskConical, Microscope, 
  Brush, PenTool, Music2, Headphones, Radio,
  Tent, Mountain, Waves, Snowflake, Flame, 
  Cat, Dog, Bird, Fish, Bug,
  Gem, Gift, ShoppingBag, ShoppingCart, CreditCard, 
  Fingerprint, ShieldCheck,
  BatteryCharging, SunMedium, MoonStar,
  Timer, AlarmClock, Hourglass, 
  MessageCircle, MessageSquare, Send, Share2,
  Trash, Edit3, UserPlus, UserMinus, GlassWater, User, AlertCircle, AlertTriangle,
  Layout
} from 'lucide-react';

export const THEME_COLORS = {
  nature: { primary: 'bg-emerald-600', hover: 'hover:bg-emerald-700', text: 'text-emerald-600', light: 'bg-emerald-50', border: 'border-emerald-200', hex: '#10b981', lightHex: '#f0fdf4' },
  ocean: { primary: 'bg-blue-600', hover: 'hover:bg-blue-700', text: 'text-blue-600', light: 'bg-blue-50', border: 'border-blue-200', hex: '#2563eb', lightHex: '#eff6ff' },
  warm: { primary: 'bg-orange-600', hover: 'hover:bg-orange-700', text: 'text-orange-600', light: 'bg-orange-50', border: 'border-orange-200', hex: '#ea580c', lightHex: '#fff7ed' },
  night: { primary: 'bg-slate-700', hover: 'hover:bg-slate-800', text: 'text-slate-700', light: 'bg-slate-100', border: 'border-slate-300', hex: '#334155', lightHex: '#f1f5f9' },
  harmony: { primary: 'bg-purple-600', hover: 'hover:bg-purple-700', text: 'text-purple-600', light: 'bg-purple-50', border: 'border-purple-200', hex: '#9333ea', lightHex: '#faf5ff' }
};

export const AVAILABLE_ICONS = [
  { id: 'Wind', icon: Wind, label: 'Feje' }, 
  { id: 'Eraser', icon: Eraser, label: 'Aftørring' },
  { id: 'Droplets', icon: Droplets, label: 'Vand' }, 
  { id: 'Trash2', icon: Trash2, label: 'Skrald' },
  { id: 'BookOpen', icon: BookOpen, label: 'Bøger' }, 
  { id: 'Apple', icon: Apple, label: 'Frugt' },
  { id: 'Utensils', icon: Utensils, label: 'Bestik' },
  { id: 'Milk', icon: Milk, label: 'Mælk' },
  { id: 'GlassWater', icon: GlassWater, label: 'Drikke' },
  { id: 'Laptop', icon: Laptop, label: 'IT/PC' }, 
  { id: 'Monitor', icon: Monitor, label: 'Skærm' },
  { id: 'Smartphone', icon: Smartphone, label: 'Mobil' },
  { id: 'Sun', icon: Sun, label: 'Ude' },
  { id: 'Trees', icon: Trees, label: 'Natur' },
  { id: 'Flower2', icon: Flower2, label: 'Blomster' },
  { id: 'Cloud', icon: Cloud, label: 'Vejr' },
  { id: 'Dumbbell', icon: Dumbbell, label: 'Idræt' }, 
  { id: 'Mic', icon: Mic, label: 'Samling' },
  { id: 'Bell', icon: Bell, label: 'Klokke' }, 
  { id: 'Key', icon: Key, label: 'Nøgler' },
  { id: 'Archive', icon: Archive, label: 'Orden' }, 
  { id: 'Music', icon: Music, label: 'Musik' },
  { id: 'Speaker', icon: Speaker, label: 'Lyd' },
  { id: 'Coffee', icon: Coffee, label: 'Køkken' }, 
  { id: 'Smile', icon: Smile, label: 'Trivsel' },
  { id: 'Heart', icon: Heart, label: 'Hjerte' },
  { id: 'Gamepad2', icon: Gamepad2, label: 'Spil' },
  { id: 'Dice5', icon: Dice5, label: 'Terning' },
  { id: 'Puzzle', icon: Puzzle, label: 'Puslespil' },
  { id: 'Paintbrush', icon: Paintbrush, label: 'Male' },
  { id: 'Scissors', icon: Scissors, label: 'Klippe' },
  { id: 'Calculator', icon: Calculator, label: 'Matematik' },
  { id: 'Globe', icon: Globe, label: 'Verden' },
  { id: 'History', icon: History, label: 'Historie' },
  { id: 'Rocket', icon: Rocket, label: 'Raket' },
  { id: 'Footprints', icon: Footprints, label: 'Gåtur' },
  { id: 'Bike', icon: Bike, label: 'Cykel' },
  { id: 'Bus', icon: Bus, label: 'Bus' },
  { id: 'Map', icon: Map, label: 'Kort' },
  { id: 'Camera', icon: Camera, label: 'Foto' },
  { id: 'Clock', icon: Clock, label: 'Tid' },
  { id: 'ClipboardCheck', icon: ClipboardCheck, label: 'Tjekliste' },
  { id: 'Award', icon: Award, label: 'Præmie' },
  { id: 'Trophy', icon: Trophy, label: 'Pokal' },
  { id: 'Shirt', icon: Shirt, label: 'Tøj' },
  { id: 'Lightbulb', icon: Lightbulb, label: 'Ide' },
  { id: 'Search', icon: Search, label: 'Søg' },
  { id: 'School', icon: School, label: 'Skole' },
  { id: 'Home', icon: Home, label: 'Hjem' },
  { id: 'Hammer', icon: Hammer, label: 'Værktøj' },
  { id: 'Wrench', icon: Wrench, label: 'Nøgle' },
  { id: 'Construction', icon: Construction, label: 'Bygge' },
  { id: 'Brain', icon: Brain, label: 'Hjerne' },
  { id: 'Pizza', icon: Pizza, label: 'Pizza' },
  { id: 'Sandwich', icon: Sandwich, label: 'Mad/Pause' },
  { id: 'Cake', icon: Cake, label: 'Fødselsdag' },
  { id: 'Car', icon: Car, label: 'Bil' },
  { id: 'Train', icon: Train, label: 'Tog' },
  { id: 'Plane', icon: Plane, label: 'Fly' },
  { id: 'Ship', icon: Ship, label: 'Skib' },
  { id: 'MapPin', icon: MapPin, label: 'Sted' },
  { id: 'Target', icon: Target, label: 'Mål' },
  { id: 'Swords', icon: Swords, label: 'Kamp' },
  { id: 'Shield', icon: Shield, label: 'Sikkerhed' },
  { id: 'Wand2', icon: Wand2, label: 'Magi' },
  { id: 'FlaskConical', icon: FlaskConical, label: 'Kemi' },
  { id: 'Microscope', icon: Microscope, label: 'Naturfag' },
  { id: 'Headphones', icon: Headphones, label: 'Høretelefoner' },
  { id: 'Radio', icon: Radio, label: 'Radio' },
  { id: 'Tent', icon: Tent, label: 'Lejr' },
  { id: 'Waves', icon: Waves, label: 'Vand/Svømning' },
  { id: 'Snowflake', icon: Snowflake, label: 'Sne' },
  { id: 'Cat', icon: Cat, label: 'Kat' },
  { id: 'Dog', icon: Dog, label: 'Hund' },
  { id: 'Bird', icon: Bird, label: 'Fugl' },
  { id: 'Bug', icon: Bug, label: 'Insekt' },
  { id: 'Gem', icon: Gem, label: 'Skat' },
  { id: 'Gift', icon: Gift, label: 'Gave' },
  { id: 'Timer', icon: Timer, label: 'Timer' },
  { id: 'AlarmClock', icon: AlarmClock, label: 'Vækkeur' },
  { id: 'Layout', icon: Layout, label: 'Andet' }
];

export const ICONS_PER_PAGE = 24;
